INSERT INTO gainz_exercises (exercise_name)
VALUES
  ('Bench press'),
  ('Bentover row'),
  ('Chest fly'),
  ('Deadlift'),
  ('Decline bench press'),
  ('Dumbbell bench press'),
  ('Dumbbell curl'),
  ('Hammer curl'),
  ('Incline bench press'),
  ('Lat pulldowns'),
  ('Leg curl'),
  ('Leg extension'),
  ('Leg press'),
  ('Lunges'),
  ('Seated row'),
  ('Shoulder press'),
  ('Shrug'),
  ('Squat'),
  ('Tricep extension'),
  ('Triceps pushdown'),
  ('Overhead press');
